const validActions = ["ActivatorRefresh", "CallManagerShowHide", "KeyPress", 
"SendKeys", "SetDynamicValue1", "SetDynamicValue2", 
"SetDynamicValue3", "SetDynamicValue4", "Audio", "AudioAuto", "AudioAutoOff", 
"AudioAutoOn", "AudioBus", "AudioBusOff", "AudioBusOn", "AudioChannelMatrixApplyPreset", 
"AudioMixerShowHide", "AudioOff", "AudioOn", "AudioPluginOff", "AudioPluginOn", 
"AudioPluginOnOff", "AudioPluginShow", "BusAAudio", "BusAAudioOff", "BusAAudioOn", 
"BusAAudioPluginOff", "BusAAudioPluginOn", "BusAAudioPluginOnOff", "BusAAudioPluginShow", 
"BusBAudio", "BusBAudioOff", "BusBAudioOn", "BusBAudioPluginOff", "BusBAudioPluginOn", 
"BusBAudioPluginOnOff", "BusBAudioPluginShow", "BusXAudio", "BusXAudioOff", 
"BusXAudioOn", "BusXAudioPluginOff", "BusXAudioPluginOn", "BusXAudioPluginOnOff", 
"BusXAudioPluginShow", "BusXSendToMaster", "BusXSendToMasterOff", "BusXSendToMasterOn", 
"BusXSolo", "BusXSoloOff", "BusXSoloOn", "MasterAudio", "MasterAudioOff", 
"MasterAudioOn", "MasterAudioPluginOff", "MasterAudioPluginOn", "MasterAudioPluginOnOff", 
"MasterAudioPluginShow", "SetBalance", "SetBusAVolume", "SetBusBVolume", 
"SetBusCVolume", "SetBusDVolume", "SetBusEVolume", "SetBusFVolume", "SetBusGVolume", 
"SetGain", "SetGainChannel1", "SetGainChannel2", "SetHeadphonesVolume", 
"SetMasterVolume", "SetVolume", "SetVolumeChannel1", "SetVolumeChannel2", 
"SetVolumeChannelMixer", "SetVolumeFade", "Solo", "SoloOff", "SoloOn", 
"CutDirect", "FadeToBlack", "QuickPlay", "SetFader", "SetTransitionDuration1", 
"SetTransitionDuration2", "SetTransitionDuration3", "SetTransitionDuration4", 
"SetTransitionEffect1", "SetTransitionEffect2", "SetTransitionEffect3", 
"SetTransitionEffect4", "Stinger1", "Stinger2", "Stinger3", "Stinger4", 
"Transition1", "Transition2", "Transition3", "Transition4", "Fullscreen", 
"FullscreenOff", "FullscreenOn", "SetOutput2", "SetOutput3", "SetOutput4", 
"SetOutputExternal2", "SetOutputFullscreen", "SetOutputFullscreen2", "Snapshot", 
"SnapshotInput", "StartExternal", "StartMultiCorder", "StartRecording", 
"StartSRTOutput", "StartStopExternal", "StartStopMultiCorder", "StartStopRecording", 
"StartStopSRTOutput", "StartStopStreaming", "StartStreaming", "StopExternal", 
"StopMultiCorder", "StopRecording", "StopSRTOutput", "StopStreaming", 
"StreamingSetKey", "StreamingSetPassword", "StreamingSetURL", "StreamingSetUsername", 
"WriteDurationToRecordingLog", "AdjustCountdown", "ChangeCountdown", "NextTitlePreset", 
"PauseCountdown", "PauseRender", "PreviousTitlePreset", "ResumeRender", 
"SelectTitlePreset", "SetCountdown", "SetImage", "SetImageVisible", "SetImageVisibleOff", 
"SetImageVisibleOn", "SetText", "SetTextColour", "SetTextVisible", "SetTextVisibleOff", 
"SetTextVisibleOn", "SetTickerSpeed", "StartCountdown", "StopCountdown", 
"SuspendCountdown", "TitleBeginAnimation", "ActiveInput", "AddInput", 
"AutoPauseOff", "AutoPauseOn", "AutoPlayFirst", "AutoPlayFirstOff", "AutoPlayFirstOn", 
"AutoPlayNext", "AutoPlayNextOff", "AutoPlayNextOn", "AutoPlayOff", "AutoPlayOn", 
"AutoRestartOff", "AutoRestartOn", "ColourCorrectionAuto", "ColourCorrectionReset", 
"CreateVirtualInput", "DeinterlaceOff", "DeinterlaceOn", "InputPreviewHide", 
"InputPreviewShow", "InputPreviewShowHide", "LayerOff", "LayerOn", "LayerOnOff", 
"ListAdd", "ListExport", "ListPlayOut", "ListRemove", "ListRemoveAll", 
"ListShowHide", "ListShuffle", "LivePlayPause", "LoopOff", "LoopOn", "MarkIn", 
"MarkOut", "MarkReset", "MarkResetIn", "MarkResetOut", "MirrorOff", "MirrorOn", 
"MoveInput", "MoveLayer", "NextItem", "NextPicture", "Pause", "Play", 
"PlayPause", "PreviewInput", "PreviewInputNext", "PreviewInputPrevious", 
"PreviousItem", "PreviousPicture", "RemoveInput", "ResetInput", "Restart", 
"SaveVideoDelay", "SelectCategory", "SelectIndex", "SetAlpha", "SetCCGainB", 
"SetCCGainG", "SetCCGainR", "SetCCGainRGB", "SetCCGammaB", "SetCCGammaG", 
"SetCCGammaR", "SetCCGammaRGB", "SetCCHue", "SetCCLiftB", "SetCCLiftG", 
"SetCCLiftR", "SetCCLiftRGB", "SetCCSaturation", "SetDynamicInput1", "SetDynamicInput2", 
"SetDynamicInput3", "SetDynamicInput4", "SetInputName", "SetLayer", "SetPanX", 
"SetPanY", "SetPictureEffect", "SetPictureEffectDuration", "SetPictureTransition", 
"SetPosition", "SetRate", "SetRateSlowMotion", "SetZoom", "SharpenOff", 
"SharpenOn", "VideoCallAudioSource", "VideoCallVideoSource", "VideoDelayStartRecording", 
"VideoDelayStartStopRecording", "VideoDelayStopRecording", "WaitForCompletion", 
"MoveMultiViewOverlay", "MultiViewOverlay", "MultiViewOverlayOff", "MultiViewOverlayOn", 
"OverlayInput1", "OverlayInput1In", "OverlayInput1Off", "OverlayInput1Out", 
"OverlayInput1Zoom", "OverlayInput2", "OverlayInput2In", "OverlayInput2Off", 
"OverlayInput2Out", "OverlayInput2Zoom", "OverlayInput3", "OverlayInput3In", 
"OverlayInput3Off", "OverlayInput3Out", "OverlayInput3Zoom", "OverlayInput4", 
"OverlayInput4In", "OverlayInput4Off", "OverlayInput4Out", "OverlayInput4Zoom", 
"OverlayInputAllOff", "PreviewOverlayInput1", "PreviewOverlayInput2", 
"PreviewOverlayInput3", "PreviewOverlayInput4", "SetMultiViewOverlay", 
"NextPlayListEntry", "PreviousPlayListEntry", "SelectPlayList", "StartPlayList", 
"StopPlayList", "ScriptStart", "ScriptStartDynamic", "ScriptStop", "ScriptStopAll", 
"ScriptStopDynamic", "ReplayACamera1", "ReplayACamera2", "ReplayACamera3", 
"ReplayACamera4", "ReplayACamera5", "ReplayACamera6", "ReplayACamera7", 
"ReplayACamera8", "ReplayBCamera1", "ReplayBCamera2", "ReplayBCamera3", 
"ReplayBCamera4", "ReplayBCamera5", "ReplayBCamera6", "ReplayBCamera7", 
"ReplayBCamera8", "ReplayCamera1", "ReplayCamera2", "ReplayCamera3", "ReplayCamera4", 
"ReplayCamera5", "ReplayCamera6", "ReplayCamera7", "ReplayCamera8", "ReplayChangeDirection", 
"ReplayChangeSpeed", "ReplayCopyLastEvent", "ReplayCopySelectedEvent", 
"ReplayDeleteLastEvent", "ReplayDeleteSelectedEvent", "ReplayDuplicateLastEvent", 
"ReplayDuplicateSelectedEvent", "ReplayExportLastEvent", "ReplayFastBackward", 
"ReplayFastForward", "ReplayJumpFrames", "ReplayJumpFramesFastOff", "ReplayJumpFramesFastOn", 
"ReplayJumpToNow", "ReplayLastEventCameraOff", "ReplayLastEventCameraOn", 
"ReplayLastEventSingleCameraOn", "ReplayLive", "ReplayLiveToggle", "ReplayMarkCancel", 
"ReplayMarkIn", "ReplayMarkInLive", "ReplayMarkInOut", "ReplayMarkInOutLive", 
"ReplayMarkInOutRecorded", "ReplayMarkInRecorded", "ReplayMarkInRecordedNow", 
"ReplayMarkOut", "ReplayMoveLastEvent", "ReplayMoveSelectedEvent", "ReplayMoveSelectedEventDown", 
"ReplayMoveSelectedEventUp", "ReplayMoveSelectedInPoint", "ReplayMoveSelectedOutPoint", 
"ReplayPause", "ReplayPlay", "ReplayPlayAllEvents", "ReplayPlayAllEventsToOutput", 
"ReplayPlayBackward", "ReplayPlayEvent", "ReplayPlayEventsByID", "ReplayPlayEventsByIDToOutput", 
"ReplayPlayEventToOutput", "ReplayPlayForward", "ReplayPlayLastEvent", 
"ReplayPlayLastEventToOutput", "ReplayPlayNext", "ReplayPlayPause", "ReplayPlayPrevious", 
"ReplayPlaySelectedEvent", "ReplayPlaySelectedEventToOutput", "ReplayRecorded", 
"ReplaySelectAllEvents", "ReplaySelectChannelA", "ReplaySelectChannelAB", 
"ReplaySelectChannelB", "ReplaySelectedEventCameraOff", "ReplaySelectedEventCameraOn", 
"ReplaySelectedEventSingleCameraOn", "ReplaySelectEvents1", "ReplaySelectEvents10", 
"ReplaySelectEvents11", "ReplaySelectEvents12", "ReplaySelectEvents13", 
"ReplaySelectEvents14", "ReplaySelectEvents15", "ReplaySelectEvents16", 
"ReplaySelectEvents17", "ReplaySelectEvents18", "ReplaySelectEvents19", 
"ReplaySelectEvents2", "ReplaySelectEvents20", "ReplaySelectEvents3", 
"ReplaySelectEvents4", "ReplaySelectEvents5", "ReplaySelectEvents6", "ReplaySelectEvents7", 
"ReplaySelectEvents8", "ReplaySelectEvents9", "ReplaySelectFirstEvent", 
"ReplaySelectLastEvent", "ReplaySelectNextEvent", "ReplaySelectPreviousEvent", 
"ReplaySetAudioSource", "ReplaySetDirectionBackward", "ReplaySetDirectionForward", 
"ReplaySetLastEventText", "ReplaySetLastEventTextCamera", "ReplaySetSelectedEventText", 
"ReplaySetSelectedEventTextCamera", "ReplaySetSpeed", "ReplayShowHide", 
"ReplayStartRecording", "ReplayStartStopRecording", "ReplayStopEvents", 
"ReplayStopRecording", "ReplaySwapChannels", "ReplayToggleLastEventCamera1", 
"ReplayToggleLastEventCamera2", "ReplayToggleLastEventCamera3", "ReplayToggleLastEventCamera4", 
"ReplayToggleLastEventCamera5", "ReplayToggleLastEventCamera6", "ReplayToggleLastEventCamera7", 
"ReplayToggleLastEventCamera8", "ReplayToggleSelectedEventCamera1", "ReplayToggleSelectedEventCamera2", 
"ReplayToggleSelectedEventCamera3", "ReplayToggleSelectedEventCamera4", 
"ReplayToggleSelectedEventCamera5", "ReplayToggleSelectedEventCamera6", 
"ReplayToggleSelectedEventCamera7", "ReplayToggleSelectedEventCamera8", 
"ReplayUpdateSelectedInPoint", "ReplayUpdateSelectedOutPoint", "ReplayUpdateSelectedSpeed", 
"ReplayUpdateSelectedSpeedDefault", "NDICommand", "NDISelectSourceByIndex", 
"NDISelectSourceByName", "NDIStartRecording", "NDIStopRecording", "PTZCreateVirtualInput", 
"PTZFocusAuto", "PTZFocusFar", "PTZFocusManual", "PTZFocusNear", "PTZFocusStop", 
"PTZHome", "PTZMoveDown", "PTZMoveDownLeft", "PTZMoveDownRight", "PTZMoveLeft", 
"PTZMoveRight", "PTZMoveStop", "PTZMoveToVirtualInputPosition", "PTZMoveToVirtualInputPositionByIndex", 
"PTZMoveUp", "PTZMoveUpLeft", "PTZMoveUpRight", "PTZUpdateVirtualInput", 
"PTZZoomIn", "PTZZoomOut", "PTZZoomStop", "LastPreset", "OpenPreset", 
"SavePreset", "DataSourceAutoNextOff", "DataSourceAutoNextOn", "DataSourceAutoNextOnOff", 
"DataSourceNextRow", "DataSourcePause", "DataSourcePlay", "DataSourcePlayPause", 
"DataSourcePreviousRow", "DataSourceSelectRow", "BrowserBack", "BrowserForward", 
"BrowserKeyboardDisabled", "BrowserKeyboardEnabled", "BrowserMouseDisabled", 
"BrowserMouseEnabled", "BrowserNavigate", "BrowserReload]";

exports.validActions = validActions;